default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vehicle_mapper
  username: vehicle_supervisor
  password: ds20g9yB76_l
  host: localhost
  port: 5432

test:
  <<: *default
  database: vehicle_mapper
  username: vehicle_supervisor
  password: ds20g9yB76_l
  host: localhost
  port: 5432


production:
  <<: *default
  database: vehicle_mapper
  username: vehicle_supervisor
  password: ds20g9yB76_l
  host: localhost
  port: 5432

# PostgreSQL. Versions 9.3 and up are supported.
